config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :restaurants, only: [:index, :show, :new, :create] do
    resources :reviews, only:[:create]
  end
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  CATEGORIES = %w(chinese italian japanese french belgian)

  has_many :reviews, dependent: :destroy

  validates :name, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true
  validates :category, presence: true, inclusion: { in: CATEGORIES }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, presence: true
  validates :rating, inclusion: { in: 0..5 }, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @review = Review.new
  end

  def new
    @restaurant = Restaurant.new
    # @restaurant = Restaurant.find(params[:restaurant_id])
    # @review = Review.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :category, :address, :phone_number)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render "restaurants/show", status: :unprocessable_entity
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<div class="container">
  <h1>Nos restaurants</h1>
  <br>
  <ul>
  <% @restaurants.each do |restaurant| %>
    <li><%= link_to restaurant.name, restaurant_path(restaurant) %>: <%= restaurant.category %></li>
  <% end %>
  </ul>

  <%= link_to "Add a new restaurant", new_restaurant_path %>
</div>

app/views/restaurants/new.html.erb
<div class="container">

  <h1>Add a new restaurant</h1>

  <%= simple_form_for @restaurant do |f| %>
    <%= f.input :name %>
    <%= f.input :category, collection: Restaurant::CATEGORIES %>
    <%= f.input :address %>
    <%= f.input :phone_number %>
    <%= f.submit "Add this restaurant", class: "btn btn-primary" %>
  <% end %>

</div>

app/views/restaurants/show.html.erb
<div class="container">

  <div class="restaurant-name">
    <h1><%= @restaurant.name %></h1>
  </div>

  <div class="category">
    <h4>Category : <%= @restaurant.category %></h4>
  </div>

  <div class="address">
    <p>Address : <%= @restaurant.address %></p>
  </div>

  <div class="phone_number">
    <p><strong>Phone Number : <%= @restaurant.phone_number %></strong></p>
  </div>
  <br>

  <div class="add-review">
    <h1>Add a new review</h1>

    <%= simple_form_for [@restaurant, @review] do |f| %>
      <%= f.input :content %>
      <%= f.input :rating, collection: (0..5) %>
      <%= f.submit "Add this review", class: "btn btn-primary" %>
    <% end %>
    </div>

    <div class="reviews">
      <h2>Reviews</h2>
      <% @restaurant.reviews.each do |review|%>
      <p><%= review.content %></p>
      <p>Rating : <%= review.rating %></p>

      <% end %>
  </div>

  <%= link_to "Back to the restaurants list", restaurants_path %>
</div>